version: "3.8"

services:
  toudoux-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11.4}
    environment:
      $FORWARDED_ALLOW_IPS: "*"
      DB_HOST: database
      DB_PASSWORD: ${DB_PASSWORD:-root}
      UVICORN_HOST: 0.0.0.0
    networks:
      - toudoux-database
      - toudoux-nginx
    expose:
      - "${PORT:-8000}"
    depends_on:
      - database

  admin:
    image: phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
    networks:
      - admin-database
      - admin-nginx
    expose:
      - "80"
    depends_on:
      - database

  database:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MARIADB_DATABASE: toudoux
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - database-storage:/var/lib/mysql
    networks:
      - admin-database
      - toudoux-database
    expose:
      - "3306"

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - admin-nginx
      - toudoux-nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - admin
      - toudoux-api

volumes:
  database-storage:

networks:
  admin-database:
  admin-nginx:
  toudoux-database:
  toudoux-nginx:
